name: Deploying React App (Timer App) to Surge
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Yarn
        run: npm install --global yarn

      - name: Install JS dependencies
        run: yarn

      - name: Test App
        run: yarn test
      
      - name: Install Surge
        run: yarn add surge
        
      - name: Build App
        run: yarn build
        
      - name: Deploy App
        run: surge ./build timer-tdd-ahmedfaraz.surge.sh --token ${{secrets.SURGE_TOKEN}}
